Version=1
# 10299.2763671875
WorldMap.CenterX=10299.2763671875

# 12645.3447265625
WorldMap.CenterY=12645.3447265625

# 16.5
WorldMap.Zoom=16.5

# true
WorldMap.Isometric=true

# true
WorldMap.ShowSymbolsUI=true

# 17.5
MiniMap.Zoom=17.5

# true
MiniMap.Isometric=true

# false
MiniMap.ShowSymbols=false

# true
MiniMap.StartVisible=true